### ISSUE TITLE
automap error

### ISSUE THREAD

**Issue by emmajoy98** [mikemahoney218/spacey#8]
My fellow peers and I are working on creating a vignette for your spacey package. We are students in Kelly Bodwin's Introduction to R class here at Cal Poly San Luis Obispo. 
We are running into issues running the automap function. If you have any troubleshooting tips we can use to utilize spacey, let us know. Below is an example.
We also would like to here suggestions on what added material you would like to be added on top of your current introduction vignette found of Github.
Thank you for your time,
331 Project Team

``` r
spacey::automap(44.121268, -73.903734)
#> Error in .local(.Object, ...) :
#> Error in value[[3L]](cond): attempt to apply non-function
```

<sup>Created on 2020-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikemahoney218** [comment]
Hey all! Thank you so much for being interested in this package!

I'll give a more thorough guesstimate of what's going on here in a little bit, but first off -- any chance you all could post the result you get from `sessionInfo()` here?

**Comment by mikemahoney218** [comment]
So the thing that's happening has nothing to do with your `sessionInfo()`, it turns out; instead, the API that I get the elevation data from isn't working the way it has been historically. I'm going to do some digging to see if this change was expected (and will try again in case it was a bug), but am thinking that their [documentation pages all being broken](https://elevation.nationalmap.gov/arcgis/sdk/rest/index.html) suggests this might be a bug on their end. I'll try to update tomorrow or the day after; sorry this times so poorly with your project starting!

**Comment by emmajoy98** [comment]
Hi Mike! Thanks for getting back so quickly! 

Glad you were able to figure it our before I got the chance to take a look back here. We'll let you work that out on your end then and check back in again when you let us know it's updated. 
No worries on the timing, there are other areas we can work on till this gets back up and running :)

**Comment by kbodwin** [comment]
Many thanks, @mikemahoney218.  :)

I'll give these groups extra time if they need it, please don't feel time pressured by us!

**Comment by mikemahoney218** [comment]
Hey all! I believe I've found the issue (the short version: the API I hit to get elevation data has become incredibly flakey, so while I used to retry it once if the attempt to download the data fails, I now need to try a lot more times than that). 

**I just pushed the version with the fix live**; if you try installing via `devtools::install_github("mikemahoney218/spacey")`, the code should work. I'll be working to get this onto CRAN shortly (and hopefully afterwards I'll find a better solution than "just keep trying").

For your question about what I'd like in new vignettes: I wrote the original vignettes very quickly, just to have any sort of overview of how the package functions up on the site. As such, it's much more my view as a developer what I think is important, rather than what a user might care about -- if you all were to play around with the functions (especially `automap`) and write up anything that seemed particularly cool or complex, that'd be super helpful.

One thing I want to mention is that this package has vignettes that every user downloads alongside the package (the [intro vignette](https://mikemahoney218.github.io/spacey/articles/introduction-to-spacey.html)) and ones that only exist on the documentation site (the [automap walkthrough](https://mikemahoney218.github.io/spacey/articles/automap-walkthrough.html)). If you make anything with a lot of pictures, we'll have to store it as the second type, as I'm pushing the limits on what CRAN will let me upload -- if you save the .Rmd in the docs/ folder rather than the vignettes/ one (and ideally [duplicate this section of code](https://github.com/mikemahoney218/spacey/blob/2bd20198e52982c4d206591077ef1e5b38db094d/prepare_branch.sh#L15) with your file's name as well, but I can handle that myself) we'll be all set for that.

**Comment by emmajoy98** [comment]
Hi Mike,
We've been able to get spacey working and have made some edits to the vignette. We're attaching a drive link so you can take a look through it and let us know if we've misinterpreted anything, or if you want to see anything else. 
Edits were made to the beginning half of the vignette, we felt we were able to understand the latter half looking at saving files and additional functionalities of the package, but if you would like those expanded upon please let us know what you'd like to see! 
https://drive.google.com/file/d/1aW5fMQJQSgVFr08aJN3T_opDP_is1O3R/view?usp=sharing
